version: '3.9'
services:
  vault-container:
    container_name: vault
    build: .
    volumes:
      - /home/vault:/home/vault
      - /home/vault/logs:/home/vault/logs
      - /home/vault/data:/home/vault/data
      - /home/vault/config:/home/vault/config 
    ports:
      - 8080:8080
      - 8081:8081
    cap_add:
      - IPC_LOCK
    logging:
      options:
        max-size: "10mb"